# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envtmpl < Formula
  desc "Executes text templates using data from environment variables and sends the result to STDOUT."
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheYkk/go-envtmpl/releases/download/v1.0.0/go-envtmpl_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "16baed5f68d5a8e7af1ef45d05cd763e43dbd5a18c1d0c936936fcb0a835e627"

      def install
        bin.install "envtmpl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheYkk/go-envtmpl/releases/download/v1.0.0/go-envtmpl_1.0.0_Darwin_arm64.tar.gz"
      sha256 "cb9c0aec47a0af18a4df5a58b2a403838067da7c042eb5282962bc878eaad04e"

      def install
        bin.install "envtmpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheYkk/go-envtmpl/releases/download/v1.0.0/go-envtmpl_1.0.0_Linux_arm64.tar.gz"
      sha256 "ec531c19afb26e87641c602436c8a25f2b3558b05332dcd653fbcf0a23ab276f"

      def install
        bin.install "envtmpl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheYkk/go-envtmpl/releases/download/v1.0.0/go-envtmpl_1.0.0_Linux_x86_64.tar.gz"
      sha256 "8b9454df361922623c2f8e5ff58c11bf4180630355c3606723085547888457b5"

      def install
        bin.install "envtmpl"
      end
    end
  end
end
