# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSwitcher < Formula
  desc "Switch between your git profiles easily"
  homepage ""
  version "0.1.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheYkk/git-switcher/releases/download/0.1.1/git-switcher_0.1.1_Darwin_arm64.tar.gz"
      sha256 "414cd7b17e7eaa2a978b6fc74631002892bcd765d239e299e63b42426a734d40"

      def install
        bin.install "git-switcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheYkk/git-switcher/releases/download/0.1.1/git-switcher_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "397ff3a1957bfa489fede1b3cd87584429082dce5f994781e98e89ba8d1a5929"

      def install
        bin.install "git-switcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TheYkk/git-switcher/releases/download/0.1.1/git-switcher_0.1.1_Linux_x86_64.tar.gz"
      sha256 "bd20627e00ebd15218fa54988eda77a4c7ec5bdb37ffc40dcfbd737553569024"

      def install
        bin.install "git-switcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheYkk/git-switcher/releases/download/0.1.1/git-switcher_0.1.1_Linux_arm64.tar.gz"
      sha256 "55a2b06ea5ad42f318d3bf4ec0b15b982d639d1e8317ab32e7f76976fb81b7de"

      def install
        bin.install "git-switcher"
      end
    end
  end
end
