# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfa < Formula
  desc "tfa is 2fa code generator cli tool"
  homepage ""
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheYkk/tfa/releases/download/v0.1.2/tfa_0.1.2_Darwin_arm64.tar.gz"
      sha256 "0e1c48b43f5eeea2faa3bca6a6ffb0df4d3079d380b4c3b8b5d31191929eb858"

      def install
        bin.install "tfa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheYkk/tfa/releases/download/v0.1.2/tfa_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "cc2fc19f03bfbaaa55cd5b16970c8bc3d24e99d5dad10fa28cf37e52ac304383"

      def install
        bin.install "tfa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TheYkk/tfa/releases/download/v0.1.2/tfa_0.1.2_Linux_x86_64.tar.gz"
      sha256 "564ad5f28fda0ea9ca5ec467a4e4b8795a86cff71047190824ba5ecb1ed074d4"

      def install
        bin.install "tfa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheYkk/tfa/releases/download/v0.1.2/tfa_0.1.2_Linux_arm64.tar.gz"
      sha256 "18decae69d46d240fca9186c937f377b8cad36ea9e0f00cf0c3684003fdf6634"

      def install
        bin.install "tfa"
      end
    end
  end
end
